### PR TITLE
Add amazonlinux2_4.14.256-197.484 kernel support

### PR DESCRIPTION
**Pull request by lucianocarranza**
Adding support for kernel 4.14.256-197.484.amzn2.x86_64 to fix the following error:

Trying to download a prebuilt falco module from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.ko
curl: (22) The requested URL returned error: 404
Unable to find a prebuilt falco module

Signed-off-by: Luciano Carranza <luchoc@gmail.com>

### CODE REVIEW

**Comment by leogr** [comment]
Hey @lucianocarranza 

The failing test reports:
```
config filename is wrong (config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml)
```

**Comment by leogr** [comment]
Hey @lucianocarranza 

Could you [sign off](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) your commit, please?
:pray:

**Comment by lucianocarranza** [comment]
Done @leogr! And thank you for reviewing the PR

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
