### PR TITLE
add missing kernel related to https://github.com/falcosecurity/test-infra/issues/496

### PR DESCRIPTION
**Pull request by bilelmoakhar**
…nfra/issues/496

### CODE REVIEW

**Comment by bilelmoakhar** [comment]
contributor.md seems to be missing, how to sign off please? https://github.com/falcosecurity/test-infra/blob/master/CONTRIBUTING.md

**Comment by leogr** [comment]
> contributor.md seems to be missing, how to sign off please? https://github.com/falcosecurity/test-infra/blob/master/CONTRIBUTING.md

Hey @bilelmoakhar 

Thank you for this PR and sorry for the inconvenience. The correct link is :point_down: 
https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md

**Comment by bilelmoakhar** [comment]
Not sure why my signoff is not accepted...

**Comment by bilelmoakhar** [comment]
closing this Pr and creating new one

**Pull request closed without merging**
