### PR TITLE
Add config for centos_4.18.0-358.el8.x86_64

### PR DESCRIPTION
**Pull request by dwindsor**
Adds configs for CentOS 8 kernels centos_4.18.0-358.el8.x86_64.

Signed-off-by: David Windsor <dwindsor@secureworks.com>

### CODE REVIEW

**Review by maxgio92 — CHANGES_REQUESTED** [review]
Hey @dwindsor thank you. Sorry by the filename `driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-358.el8.x86_64.yaml` shoudl be `driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-358.el8.x86_64_1.yaml`

**Comment by dwindsor** [comment]
> Hey @dwindsor thank you. Sorry, but the filename `driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-358.el8.x86_64.yaml` should be `driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-358.el8.x86_64_1.yaml`. Could you fix it? Thank you very much!

Thanks for pointing this out! I noticed that you suggested changes, but I already pushed a commit that accomplishes the rename.

**Review by maxgio92 — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
