### PR TITLE
falcosidekick: add required ci checks

### PR DESCRIPTION
**Pull request by cpanato**
falcosidekick: add required ci checks

/assign @leogr

### CODE REVIEW

**Review by leodido — COMMENTED** [review]
Shouldn't this go towards the new Prow config path (ie., `config/config.yaml`)?

**Comment by cpanato** [comment]
@leodido @leogr humm, i saw that just now, we have the config in two places. which one is the correct to use?

**Comment by leodido** [comment]
The new Prow is at `config/config.yaml` Carlos :)

**Review by leodido — APPROVED** [review]
Great!

Thanks, Carlos 🥳

**Pull request merged**
