### PR TITLE
chore(config): added tests-integration-arm64 to Falco required_status _checks

### PR DESCRIPTION
**Pull request by FedeDP**
https://github.com/falcosecurity/falco/pull/2099 is introducing arm64 integration tests for Falco.
Open this one in wip to avoid forgetting :)

### CODE REVIEW

**Comment by FedeDP** [comment]
2099 is now merged and this is good now.

**Review by zuc — APPROVED** [review]

**Comment by FedeDP** [comment]
Why did this trigger the `build-new-drivers-centos-` jobs :/

**Review by zuc — APPROVED** [review]

**Pull request merged**
