### PR TITLE
new(driverkit): added 4.0.0+driver driverversion.

### PR DESCRIPTION
**Pull request by FedeDP**
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

### CODE REVIEW

**Comment by FedeDP** [comment]
Rebased on top of master.

**Review by leogr — APPROVED** [review]
ok for me

/approve

/hold because maintenance tasks are ongoing

@FedeDP Feel free to unblock when needed

**Comment by leogr** [comment]
Closing and reopening to trigger the CI check: `check-prow-config Expected — Waiting for status to be reported`

/close

**Pull request merged**
