### PR TITLE
Add postsubmit job to sync Peribolos GitHub Teams from OWNERS

### LINKED ISSUE #777: Automatically sync `config/org.yaml` when an `OWNERS` file gets updated
**Motivation**

We need to automate the way we manage repository permissions.

On the one hand, `OWNERS` files are honored by Prow. On the other hand, GitHub uses its settings which are enforced by Peribolos that applies settings we commit to [config/org.yaml](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml).

Unfortunately, there's no automatic mechanism to sync the two. And manually synching them can't scale (see https://github.com/falcosecurity/test-infra/pull/776).

**Feature**

Introduce a mechanism to automatically update [config/org.yaml](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml) when an `OWNERS` file gets updated.

**Alternatives**

Manual synch. Honestly, it's a pain.

**Additional context**

### PR DESCRIPTION
**Pull request by maxgio92**
The post-submit Prow Job runs on changes on OWNERS files - i.e. in the evolution repository.

It synchronizes the Peribolos config - in the test-infra repository - updating the specified evolution-maintainers GitHub Team, with the additional approvers specified in the OWNERS file.

More [here](https://github.com/maxgio92/peribolos-syncer/blob/v0.1.0/docs/peribolos-syncer_sync_github.md#peribolos-syncer-sync-github).

Closes #777

### CODE REVIEW

**Comment by maxgio92** [comment]
PTAL @leogr. WDYT?

A demo PR is #1117

**Review by leogr — COMMENTED** [review]
It seems great! I reserve some time for a second look. Meanwhile a question: can we enable it for all repos without the need of copy/paste the job? We use OWNERS the n all repos.

**Comment by maxgio92** [comment]
I don't think so @leogr because the flow is to react to changes to the leaf OWNERS file, when PRs are merged, on the main branch, on the single repositories.

So I think we need anyway one postsubmit Prow job, per repository. WDYT?

**Comment by leogr** [comment]
In my experience copy/paste has been very error prone in this context. However, if there's no alternative, we have to deal with it :)

Further question: does it work with nested OWNERS files? We can have multiple OWNERS in a repo, with some of them in subfolders.

**Comment by maxgio92** [comment]
@leogr I see your point. In order to provide granularity with an event-based pull approach like this with jobs I'm not sure we can deal with it. An alternative - it could be a next version - is by using a global webhook (maybe a Prow plugin as @jasondellaluce suggested).

As of now it doesn't support an OWNERS tree but only a specified one (i.e. the leaf approvers declared in the in the root OWNERS file). Anyway the support can be added easily (the underlying owners package already supports it).

**Comment by maxgio92** [comment]
Question: do you think @leogr in our use case, an approver for a particular sub-part of a repository, should be the member of the related repository's maintainers GitHub team?

**Comment by leogr** [comment]
> Question: do you think @leogr in our use case, an approver for a particular sub-part of a repository, should be the member of the related repository's maintainers GitHub team?

It should, and we are already following this pattern AFAIK

**Comment by maxgio92** [comment]
I agree @leogr. Considering this point I'd keep this PR on hold, until the feature is implemented in the tool.

/hold

**Comment by maxgio92** [comment]
/unhold

Implemented the change @leogr

**Review by leogr — COMMENTED** [review]
/lgtm

just waiting for a second opinion cc @FedeDP

**Review by FedeDP — APPROVED** [review]
LGTM!
Thank you @maxgio92 !
/approve

**Pull request merged**
