### PR TITLE
Add DBG configurations for 13ec67 version

### PR DESCRIPTION
**Pull request by maxgio92**
This PR adds Driverkit Build Grid configurations for 13ec67ebd23417273275296813066e07cb85bc91 version of drivers.

### CODE REVIEW

**Review by leodido — APPROVED** [review]
Thanks

**Review by leogr — APPROVED** [review]
/hold cancel 
since https://github.com/falcosecurity/falco/pull/1552 got merged

**Comment by maxgio92** [comment]
Jobs re-triggered due to #379 by [update-jobs-pr](https://prow.falco.org/view/s3/falco-prow-logs/logs/update-jobs-pr/1396821727752753152) run.
This makes me think that a more fine-grained jobs grid can be convenient with different pros.

**Pull request merged**
