### PR TITLE
bulk update and cleanup of config/org.yaml

### PR DESCRIPTION
**Pull request by leogr**
This PR synchs the [config/org.yaml](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml) with `OWNERS` files from all repositories and updates the repository status (ie. remove teams from archived repositories).

All details are in commits' messages.

### CODE REVIEW

**Comment by leogr** [comment]
PS

I hope we will automate this one day :smiling_face_with_tear: 
I'm going to open an issue.

**Review by maxgio92 — APPROVED** [review]
/approve

**Pull request merged**
