### PR TITLE
Adding additional driverkit for amazonlinux2

### PR DESCRIPTION
**Pull request by mcbarzi**
Adding new driverkit for amazonlinux2
Related to [#652 ](https://github.com/falcosecurity/test-infra/issues/652)

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
Hey @mcbarzi 

Thank you for this PR! It SGTM, however, could you add the same config also to other driver versions?

For example, it is missing also in `b7eb0dd65226a8dc254d228c8d950d07bf3521d2`.

:pray:

**Comment by mcbarzi** [comment]
> 

Added to other versions as well

**Review by zuc — APPROVED** [review]
/approve

**Comment by mcbarzi** [comment]
hi, Upon checking the driverkit for driver version 17f5df52a7d9ed6bb12d3b1768460def8439936d wasn't successfully built
```
utils/checkfiles config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.268-205.500.amzn2.x86_64_1.yaml
DRIVERKIT=/bin/driverkit S3_DRIVERS_BUCKET="falco-distribution" S3_DRIVERS_KEY_PREFIX="driver" SKIP_EXISTING=true utils/build config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.268-205.500.amzn2.x86_64_1.yaml
INFO using config file                             file=config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.268-205.500.amzn2.x86_64_1.yaml
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="Error: No such container:path: 1326dac9dc0cbcf7103930cc2702a2b6dd08160fa3be64bb1f0ead6ad2d8ec08:/tmp/driver/module.ko"
```

**Pull request merged**
