### PR TITLE
update(OWNERS): adding jonahjon and maxgio92

### PR DESCRIPTION
**Pull request by leodido**
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>

As per the last Falco Infra WG Call, we welcome 🥳  @jonahjon and @maxgio92 in the test-infra maintainers!

Recap in the [mailing list](https://lists.cncf.io/g/cncf-falco-dev/message/170).

### CODE REVIEW

**Comment by leodido** [comment]
Screenshot 2020-10-05 at 16 30 21

Waiting for @jonahjon to accept the organization and team invitation!

**Comment by leodido** [comment]
thank you my friend @poiana 👍

**Comment by maxgio92** [comment]
Thank you @leodido , this is an honor!

**Comment by jonahjon** [comment]
Thank you so much @Leonardo Di Donato <leodidonato@gmail.com> this is super
exciting and I can't wait for everything going forward.

**Review by fntlnz — APPROVED** [review]

**Pull request merged**
