### PR TITLE
update(config/jobs/build-libs): add build job for WITH_CHISEL option

### PR DESCRIPTION
**Pull request by leogr**
/hold
See https://github.com/falcosecurity/libs/pull/14

### CODE REVIEW

**Comment by jonahjon** [comment]
The job looks good, the PR might need to be updated or refreshed, not sure if Prow can retroactively add to an open PR though if that was the goal.

**Comment by leogr** [comment]
> The job looks good, the PR might need to be updated or refreshed, not sure if Prow can retroactively add to an open PR though if that was the goal.

No need to retroactively add to an open PR, because those PRs that will touch the functionality will need a rebase. So we will manually handle that anyways.

**Review by jonahjon — COMMENTED** [review]
lgtm, see you got a hold on still too.

**Review by leodido — APPROVED** [review]

**Comment by leogr** [comment]
/hold cancel
Since https://github.com/falcosecurity/libs/pull/14 has been merged

**Pull request merged**
