### PR TITLE
fix: Add configs for CentOS 8.0, 8.1, 8.2 and 8.3

### PR DESCRIPTION
**Pull request by dwindsor**
Adds configs for remaining CentOS 8 kernels.

Signed-off-by: David Windsor <dwindsor@secureworks.com>

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
Could you add the same configuration for the latest driver version `319368f1ad778691164d33d59945e00c5752cd27` too?

Otherwise, LGTM.

Thanks in advance :pray:

**Comment by dwindsor** [comment]
> 

Submitted configs for latest driverversion (`319368f1ad778691164d33d59945e00c5752cd27`).

**Review by maxgio92 — APPROVED** [review]
/approve

**Pull request merged**
