### PR TITLE
Create ubuntu-aws_5.4.0-1060-aws_63

### PR DESCRIPTION
**Pull request by yogisec**
Creating the objects for ubuntu-aws_5.4.0-1060-aws_63

Signed-off-by: Travis Lowe <yogisec7@gmail.com>

### CODE REVIEW

**Comment by maxgio92** [comment]
Hello @yogisec , thank you. Let's test it!
/ok-to-test

**Comment by yogisec** [comment]
closes #576

**Review by maxgio92 — APPROVED** [review]
/approve

**Comment by evanmcclure** [comment]
So fixed. So fast. So swole. Thank you!

**Pull request merged**
