### PR TITLE
Adding new driverkit for amazonlinux2_4.14.275-207.503.amzn2.x86_64_1

### PR DESCRIPTION
**Pull request by mcbarzi**
Signed-off-by: MCBarzi <mcbarzi@github.com>

### CODE REVIEW

**Comment by mcbarzi** [comment]
Signed-off-by: MCBarzi <mcbarzi@github.com>

**Comment by maxgio92** [comment]
Hey @mcbarzi , thank you!

**Review by maxgio92 — APPROVED** [review]
/approve

**Comment by maria-barcena-phx** [comment]
hi @maxgio92 , seeing this error in the job https://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_test-infra/742/build-new-drivers-amazonlinux2-presubmit/1541688127691689984
```
359.amzn2.x86_64_1.o)
utils/checkfiles config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
DRIVERKIT=/bin/driverkit S3_DRIVERS_BUCKET="falco-distribution" S3_DRIVERS_KEY_PREFIX="driver" SKIP_EXISTING=true utils/build config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
INFO using config file                             file=config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="\"specify container image platform\" requires API version 1.41, but the Docker daemon API version is 1.38"
utils/checkfiles config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_4.14.243-185.433.amzn2.x86_64_1.yaml
```

**Pull request merged**
