### PR TITLE
Poiana wants to update its new GPG key's fingerprint

### LINKED ISSUE #354: @poiana's commit signature doesn’t match the committer email
**Describe the bug**

@poiana's commits are not verified anymore, because the email in the commit signature doesn’t match the committer email.
The issue was introduced by #336

**How to reproduce it**

Just take a look to a PR opened by @poiana , for example: https://github.com/falcosecurity/evolution/pull/55

**Expected behaviour**

**Screenshots**

Screenshot from 2021-03-31 09-22-55

### PR DESCRIPTION
**Pull request by maxgio92**
In this PR poiana updates its brand new GPG key's fingerprint.
The key has already been updated in the cluster and authorized as you can see by this PR commits.

Fixes #354 (when also the key in Prow will be rotated).

### CODE REVIEW

**Comment by maxgio92** [comment]
/hold

This PR needs then to rotate the GPG key `Secret` in Prow, to match the updated fingerprint that will PR brings.

**Review by leogr — COMMENTED** [review]
`check-prow-config` is failing with the following message:

```json
{
  "component": "unset",
  "error": "dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.",
  "file": "prow/io/opener.go:128",
  "func": "k8s.io/test-infra/prow/io.createGCSClient",
  "level": "debug",
  "msg": "Cannot load application default gcp credentials, falling back to anonymous client",
  "severity": "debug",
  "time": "2021-11-23T21:11:57Z"
}{
  "component": "unset",
  "file": "prow/cmd/checkconfig/main.go:90",
  "func": "main.reportWarning",
  "level": "warning",
  "msg": "the following orgs or repos forbid the do-not-merge/release-note-label-needed label for merging but do not enable the release-note plugin: [repo: falcosecurity/katacoda-scenarios]",
  "severity": "warning",
  "time": "2021-11-23T21:11:57Z"
}{
  "component": "unset",
  "file": "prow/cmd/checkconfig/main.go:90",
  "func": "main.reportWarning",
  "level": "warning",
  "msg": "the following jobs use the kubernetes provider but do not use the pod utilities: [arm-build-falco arm-build-falco-grpc]",
  "severity": "warning",
  "time": "2021-11-23T21:11:57Z"
}
```

The first error is something I can't understand at the moment.

The second is a misconfiguration for that repo (I will take a look at it and fix it eventually).

The last is likely a misconfiguration too, but I have to dig deeper to understand which configuration causes the issue.

**Review by leogr — APPROVED** [review]

**Pull request merged**
