### PR TITLE
Add new AmazonLinux2 EKS AMI kernel

### PR DESCRIPTION
**Pull request by Kostavro**
Hello,

reading older similar PRs, I thought perhaps this is the way to go in order to solve https://github.com/falcosecurity/falco/issues/1643 ?

### CODE REVIEW

**Comment by maxgio92** [comment]
Hi all,
Terrascan just introduced new recommended policy rules for our infra, which prevented CI to pass.
#388 should unblock also this PR.

**Comment by maxgio92** [comment]
Hey @Kostavro sorry about that, we're solving issue on infra CI. I'll keep you posted

**Comment by Kostavro** [comment]
No worries @maxgio92. I also have to let you know that I found driver falco_amazonlinux2_5.4.110-54.182.amzn2.x86_64_1.ko is available at the falco server since I opened this - not sure about the timezone of the upload and if that's somehow related to this PR though.

**Comment by maxgio92** [comment]
Thanks @Kostavro to note that, we'll check on it. In the meantime could you please rebase your branch on master? Thanks

**Comment by maxgio92** [comment]
Thanks @Kostavro !

**Review by maxgio92 — APPROVED** [review]

**Pull request merged**
