### PR TITLE
Update driver configurations (2020-11-25)

### PR DESCRIPTION
**Pull request by leodido**
Prebuilt drivers update

Also configures 5c0b863ddade7a45568c0ac97d037422c9efb750 driver version (for the upcoming Falco 0.27 release)

### CODE REVIEW

**Review by fntlnz — APPROVED** [review]

**Review by jonahjon — APPROVED** [review]

**Review by jonahjon — DISMISSED** [review]

**Comment by jonahjon** [comment]
I think the DCO commit is causing the /retest to not work?

**Comment by leodido** [comment]
Does `test-infra` miss the `trigger` plugin? hmmmm

**Comment by jonahjon** [comment]
> Does `test-infra` miss the `trigger` plugin? hmmmm

I have no proof of this, but so fa rit appears jobs only occur after a GH review is added /lgtm are on PR's. This would for sure cause some issues re-requesting reveiws just to re-run tests going forward.

**Review by jonahjon — APPROVED** [review]

**Review by jonahjon — APPROVED** [review]

**Comment by jonahjon** [comment]
For the record the job did pass, maybe because it took so long prow didn't update the status.  https://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_test-infra/251/build-drivers-debian-presubmit/1337553199640350720

**Pull request merged**
