### PR TITLE
update(docs): add LucaGuerra as owner

### PR DESCRIPTION
**Pull request by LucaGuerra**
Over the last couple of years I have contributed to this repo, especially with security/auth scripts. As a core maintainer, I would like to help with maintenance of this repo.

### CODE REVIEW

**Comment by LucaGuerra** [comment]
/hold

for vote as per governance

**Comment by FedeDP** [comment]
Big +1 from me!

**Comment by leogr** [comment]
big +1 for me too

**Comment by maxgio92** [comment]
Big +1 for me too!

**Review by leogr — APPROVED** [review]
Great! This has been open for a week and more, also we have more vote in favor than against.
So 
/approve

🥳 

/hold cancel

**Pull request merged**
