### PR TITLE
new(driverkit/config): add driver version b7eb0dd

### PR DESCRIPTION
**Pull request by LucaGuerra**
Signed-off-by: Luca Guerra <luca@guerra.sh>

Build drivers for version `b7eb0dd65226a8dc254d228c8d950d07bf3521d2`, which is used by the upcoming Falco 0.31.1 (see https://github.com/falcosecurity/falco/issues/1924)

### CODE REVIEW

**Review by leogr — APPROVED** [review]

**Comment by leogr** [comment]
/approve

:tada:

**Comment by zuc** [comment]
/test build-new-drivers-amazonlinux2-presubmit 
🙄

**Comment by zuc** [comment]
/test build-new-drivers-centos-presubmit
🤬

**Comment by zuc** [comment]
/skip build-new-drivers-amazonlinux-presubmit
/skip build-new-drivers-ubuntu-generic-4-presubmit

As they already ran yesterday

**Pull request merged**
