### PR TITLE
new(iam): add Falco ECR access

### PR DESCRIPTION
**Pull request by LucaGuerra**
This is remarkably similar to the falcosidekick one, that's because it's what we need for https://github.com/falcosecurity/falco/pull/2501 . Will need to be merged after https://github.com/falcosecurity/test-infra/pull/1102 .

### CODE REVIEW

**Comment by LucaGuerra** [comment]
/hold

until https://github.com/falcosecurity/test-infra/pull/1102 is merged

**Review by maxgio92 — DISMISSED** [review]
thanks @LucaGuerra 

/approve

**Comment by maxgio92** [comment]
@LucaGuerra please rebase on master and feel free to unhold it :)

**Comment by FedeDP** [comment]
If you rebase we are :ok:

**Comment by LucaGuerra** [comment]
On it!

**Comment by LucaGuerra** [comment]
Rebased

/unhold

**Review by FedeDP — APPROVED** [review]
/approve 
@maxgio92 :P

**Pull request merged**
