### PR TITLE
adding amazonlinux2_5.4.204-113.362.amzn2

### PR DESCRIPTION
**Pull request by irivera007**
adding to the missing 2.0.0 driver
Signed-off-by: Izak R [irivera007](mailto:irivera007@yahoo.com)

### CODE REVIEW

**Comment by maxgio92** [comment]
Hi @irivera007! Thank you and welcome!
Could you please DCO sign your commit?

**Comment by irivera007** [comment]
@maxgio92 thank you so much for taking a look, I just sent another signed commit, let me know if I need anything else

**Comment by apetrosyan1613** [comment]
Hello! Any updates for this pr?)

**Review by maxgio92 — APPROVED** [review]
/approve

**Pull request merged**
