### PR TITLE
new(config): added ubuntu azure, gke, gcp flavors jobs.

### PR DESCRIPTION
**Pull request by FedeDP**
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

### CODE REVIEW

**Comment by FedeDP** [comment]
/hold

Given that no currently existing falco-driver-loader is able to load these drivers, it makes no sense to merge this now.
TO BE MERGED once drivers for Falco 0.33 are tagged.

**Review by leogr — APPROVED** [review]
LGTM.

@FedeDP feel free to unhold at the right time

**Comment by FedeDP** [comment]
Rebased on top of master @leogr

**Review by leogr — DISMISSED** [review]
/approve

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
