### PR TITLE
new(ci): added gha.

### PR DESCRIPTION
**Pull request by FedeDP**

### CODE REVIEW

**Comment by FedeDP** [comment]
Pre submit job is ok. Here the hard part is fixing up post submit jobs.

**Comment by maxgio92** [comment]
Thanks @FedeDP, just a note to keep in mind. It would optimal if the Terraform job would you the version specified in the code (something like [this rude trick](https://github.com/falcosecurity/test-infra/blob/master/tools/terraform.Makefile#L1)

**Comment by LucaGuerra** [comment]
@maxgio92 I believe `deploy_terraform.sh` already does this

**Comment by FedeDP** [comment]
Note this also needs https://github.com/falcosecurity/test-infra/pull/1159.

**Comment by FedeDP** [comment]
I'll remove the wip and put this on hold since it is reviewable now, but still needs #1159 first.

**Comment by leogr** [comment]
Screenshot from 2023-05-18 17-47-11
Nice :thinking:

**Comment by FedeDP** [comment]
Yep it's because i deleted the whole workflow for circleci; it's not important.

**Review by leogr — DISMISSED** [review]
LGTM.

I'd like just to have a second look from @maxgio92, so:
/hold

feel free to remove the _hold_ at any time

**Review by maxgio92 — DISMISSED** [review]
Sorry all for the delay.
 
/approve

**Comment by FedeDP** [comment]
We also need #1159 before :)

**Review by LucaGuerra — APPROVED** [review]

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
