### PR TITLE
Create debian_5.10.0-10

### PR DESCRIPTION
**Pull request by movd**
Signed-off-by: Moritz von Doetinchem <moritz.doetinchem@dg-i.net>

### CODE REVIEW

**Comment by Issif** [comment]
hello @movd,

Thank you for your PR. It's really valuable for the whole community.

We have issues with the current version of `driverkit` for building drivers for kernels > 5.x. See https://github.com/falcosecurity/driverkit/pull/111 which fixes that.

We need to release a new version of driverkit, I'm asking to maintainers what's situation.

**Comment by movd** [comment]
Ah, I thought I tried it since it's merged now.

**Review by maxgio92 — APPROVED** [review]
/approve

**Pull request merged**
