### PR TITLE
Adding 4 additional al2 kernels

### PR DESCRIPTION
**Pull request by abroglesc**
Signed-off-by: Austin Brogle <abrogle@snapchat.com>

Adding in 4 additional AL2 kernels to be built for latest driver version shipped in 0.31.0 :)

### CODE REVIEW

**Comment by zuc** [comment]
Hi @abroglesc - thanks for your contrib!
Would you mind adding support for the other driver versions as well? 🙏

**Review by leogr — APPROVED** [review]
/approve

Thank you!

**Pull request merged**
