### PR TITLE
new(driverkit): add a new driver version `7.0.0+driver` and remove the old `4.0.0+driver`

### PR DESCRIPTION
**Pull request by Andreagit97**
This PR adds a new driver version `7.0.0+driver` and removes the old `4.0.0+driver`

### CODE REVIEW

**Comment by FedeDP** [comment]
> +50,329 −50,591

I'd expect + and - to be equal!

**Comment by Andreagit97** [comment]
not necessary, to craft `7.0.0+driver` folder I used the last one `6.0.1+driver`, and not the one I removed (`4.0.0+driver`). Probably the `4.0.0+driver` folder contains more configs :thinking:

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
> Probably the 4.0.0+driver folder contains more configs 🤔

That is not possible because all configs are generated with `dbg-go` from kernel crawler output. Indeed:
```
✗ (1.6ms) 11:13:46 [federico][fededp-sysdig][master][~/Work/test-infra/driverkit/config/4.0.0+driver] $ ls x86_64/ | wc -l
4275
✓ (30.0ms) 11:13:51 [federico][fededp-sysdig][master][~/Work/test-infra/driverkit/config/4.0.0+driver] $ ls aarch64/ | wc -l
2577
✓ (19.9ms) 11:13:55 [federico][fededp-sysdig][master][~/Work/test-infra/driverkit/config/4.0.0+driver] $ cd ../6.0.1+driver/
✓ (2.0ms) 11:13:58 [federico][fededp-sysdig][master][~/Work/test-infra/driverkit/config/6.0.1+driver] $ ls aarch64/ | wc -l
2577
✓ (21.6ms) 11:14:00 [federico][fededp-sysdig][master][~/Work/test-infra/driverkit/config/6.0.1+driver] $ ls x86_64/ | wc -l
4275
```

Weird :/

**Comment by FedeDP** [comment]
Let's go on anyway, since worst case tomorrow kernel-crawler run will fix everything for us.

**Pull request merged**
