### PR TITLE
wip: declare the infrastructre on aws as code

### PR DESCRIPTION
**Pull request by maxgio92**
This is a work in progress aimed to declare and manage the Prow AWS infrastructure (and not only with other Terraform providers like the kubernetes one).
For now the code declares a basic and standard infrastructure with AWS EKS.

### CODE REVIEW

**Comment by jonahjon** [comment]
This has some conflicting changes for sure, so let's be careful to NOT update existing prow once this is merged in..... until the prow microservice yaml's get updated too.

**Comment by maxgio92** [comment]
@jonahjon I declared the Prow storage on Terraform and removed the related step on `deploy.sh` script as it's now part of the IaC

**Comment by maxgio92** [comment]
I think we can close this in favor of [197](https://github.com/falcosecurity/test-infra/pull/197)

**Comment by jonahjon** [comment]
+1

> I think we can close this in favor of [197](https://github.com/falcosecurity/test-infra/pull/197)

+1

**Comment by nibalizer** [comment]
#197 is closed - which is the right PR?

**Comment by jonahjon** [comment]
> #197 is closed - which is the right PR?

I closed #197 because I didn't DCO signoff all my commits on it.... need to figure out a cleaner way to do that

**Comment by nibalizer** [comment]
You can git `commit -s --amend` on a single commit

To do a sequence do:

`git rebase -i HEAD~7` replacing 7 with whatever number of commits you need to do.

Change all the picks to 'e' for 'edit'

Then for every commit do:

`git commit -s --amend`
`git rebase --continue`

**Comment by jonahjon** [comment]
> You can git `commit -s --amend` on a single commit
> 
> To do a sequence do:
> 
> `git rebase -i HEAD~7` replacing 7 with whatever number of commits you need to do.
> 
> Change all the picks to 'e' for 'edit'
> 
> Then for every commit do:
> 
> `git commit -s --amend`
> `git rebase --continue`

That was a huge help thanks ...... #197  is all signed off now!

**Comment by maxgio92** [comment]
Closed in favor of #198

**Pull request closed without merging**
