### PR TITLE
build ko 5.4.181-99.354.amzn2.x86_64

### PR DESCRIPTION
**Pull request by Kaizhe**
Signed-off-by: Kaizhe Huang <khuang@aurora.tech>

### CODE REVIEW

**Comment by zuc** [comment]
Hey @Kaizhe, thanks for this PR.
Tests are failing because `kernelrelease` is malformed (`_64` is missing at the end of the string).

Could you please fix that?
Thanks 🙏

**Review by leogr — APPROVED** [review]
/approve

**Comment by goroi** [comment]
Hello @Kaizhe do you happen to know why this kernel module still is not present for download.
`
https://download.falco.org/driver/319368f1ad778691164d33d59945e00c5752cd27/falco_amazonlinux2_5.4.181-99.354.amzn2.x86_64_1.ko
`

**Pull request merged**
