### PR TITLE
refactor(images/autobump): make bump of component and config optional

### PR DESCRIPTION
**Pull request by maxgio92**
This PR allows to autobump components and Prow config separately.

For example it could be bumped a Peribolos job only, without the requirement of having Prow config in place.

### CODE REVIEW

**Comment by leogr** [comment]
/remove-lifecycle stale

Hey @maxgio92 

Sorry, I lost track of this. I guess it needs at least a rebase to update the CI checks.

cc @FedeDP

**Comment by maxgio92** [comment]
Hi @leogr, no worries. I think we should close this in favor of the new autobumper.

@cappellinsamuele working on that already :) And #1132 will definitely superseed this.

WDYT?

**Comment by leogr** [comment]
> Hi @leogr, no worries. I think we should close this in favor of the new autobumper.
> 
> @cappellinsamuele working on that already :) And #1132 will definitely superseed this.
> 
> WDYT?

Ok, for me!

I just wanted to sort this out :smiley_cat:

**Comment by FedeDP** [comment]
Given that autobump script is no more existent, is this still needed?
@maxgio92

**Comment by maxgio92** [comment]
You're right, totally agree @FedeDP, thank you.

/close

**Pull request closed without merging**
