### PR TITLE
Add config for amazonlinux2_5.4.172-90.336

### PR DESCRIPTION
**Pull request by samuellg**
This PR adds support for amazonlinux2_5.4.172-90.336

### CODE REVIEW

**Comment by samuellg** [comment]
Hi @leodido and @poiana, let me know if anything is missing in this PR, thanks !

**Comment by leogr** [comment]
> Hi @leodido and @poiana, let me know if anything is missing in this PR. Thanks !

Hey @samuellg 

Thank you for this PR! 

It SGTM, I'm just waiting for the CI before giving my final approve :+1:

**Comment by ThibaultLengagne** [comment]
Hello,

We would need this PR merged also :+1:

**Review by leogr — APPROVED** [review]
/approve

**Comment by samuellg** [comment]
Thanks ! :)

**Pull request merged**
