### PR TITLE
updating eks version 1.19

### PR DESCRIPTION
**Pull request by jonahjon**
Signed-off-by: jonahjon <jonahjones094@gmail.com>

Adding node group version bump since they are still on 1.17.

`v1.17.12-eks-7684af`

### CODE REVIEW

**Comment by danpopSD** [comment]
/lgtm 
/approved

@maxgio92 / @leodido  @leogr    not sure im an approver yet :)

**Comment by maxgio92** [comment]
Hey @danpopSD ! Not yet :D If you want you can join!

@jonahjon I left only a little comment on documentation `TERRAFORM.md`. Apart from that, that's ok for me!

/appro

**Review by maxgio92 — CHANGES_REQUESTED** [review]
I think terraform should be exactly 0.14.11

**Review by maxgio92 — APPROVED** [review]
/approve

**Pull request merged**
