### PR TITLE
new(driverkit/config): add driver version 39ae7d40496793cf3d3e7890c9bbdc202263836b

### PR DESCRIPTION
**Pull request by FedeDP**
They will be used by Falco 0.32.0 that is currently freezing libs version.
Wip for now until https://github.com/falcosecurity/falco/pull/2024 is merged.

### CODE REVIEW

**Review by leogr — APPROVED** [review]
This is the candidate driver version for Falco 0.32

/approve

I'm putting this on hold while we are testing the latest build of Falco

/hold

Once we are confident that Falco works as expected with this driver version, feel free to unhold.

Thank you :pray:

**Comment by FedeDP** [comment]
poiana :pray:

**Review by leogr — APPROVED** [review]

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
