### PR TITLE
update: set release branch 0.13.x as protected

### PR DESCRIPTION
**Pull request by Andreagit97**
/hold until the end of the release

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
/approve

**Comment by leogr** [comment]
Hey @Andreagit97 

We should protect the branch once it has been created :point_down:
https://github.com/falcosecurity/libs/blob/master/release.md#release-branch

> Once the release brach has been created:
> 
>  - A PR must be opened in our [test-infra](https://github.com/falcosecurity/test-infra/blob/master/config/config.yaml) repository to set the newly created branch as protected.
> 
>  - A release candidate tag should be created in the release branch for testing purposes.

Thus, could we remove the `hold`?

**Pull request merged**
