### PR TITLE
Support for 5.4.156-83.273.amzn2.x86_64

### PR DESCRIPTION
**Pull request by henriblancke**
Adds support for `5.4.156-83.273.amzn2.x86_64` amazon linux kernel

### CODE REVIEW

**Comment by maxgio92** [comment]
Hello @henriblancke , thank you.
Would you mind doing:
- a rebase on master branch and
- adding also the config for the other  two Falco driver versions?
  - [3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4](https://github.com/falcosecurity/test-infra/tree/master/driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
  - [5c0b863ddade7a45568c0ac97d037422c9efb750](https://github.com/falcosecurity/test-infra/tree/master/driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750)

Thanks

**Comment by henriblancke** [comment]
@maxgio92 it looks like someone else added the drivers in this PR recently. Everything works on our end now and the driver seems to be available. Do you want me to just close this PR?

**Comment by maxgio92** [comment]
Ops you're right :) yes, please. Thanks for your time!

**Pull request closed without merging**
