### PR TITLE
update(config): update k8s to 1.21.

### PR DESCRIPTION
**Pull request by FedeDP**
/cc @maxgio92

### CODE REVIEW

**Comment by FedeDP** [comment]
We will probably need to manually merge this one since we broke prow :cry:

**Comment by LucaGuerra** [comment]
@FedeDP makes sense. Since this is blocking all the repos, I'm going to manually merge this!

**Review by maxgio92 — APPROVED** [review]

**Comment by maxgio92** [comment]
Thank you @LucaGuerra

**Pull request merged**
