### PR TITLE
Update drivers (2020-12-17)

### PR DESCRIPTION
**Pull request by fntlnz**
Updating the drivers...

### CODE REVIEW

**Review by leodido — APPROVED** [review]

**Comment by leodido** [comment]
Let's gooooo 🥳

**Comment by jonahjon** [comment]
O noooooo this shouldn't have happened

**Comment by jonahjon** [comment]
These build-jobs should have never gotten pulled into this PR..... not sure why they are triggering `    run_if_changed: '^images/update-jobs/'`

**Comment by leodido** [comment]
> These build-jobs should have never gotten pulled into this PR..... not sure why they are triggering ` run_if_changed: '^images/update-jobs/'`

Don't really know atm.

Maybe we need backslashes '^images\/update-jobs\/' ?

**Review by jonahjon — APPROVED** [review]

**Review by jonahjon — APPROVED** [review]

**Pull request merged**
