### PR TITLE
Add 5.4.95-42.163.amzn2.x86_64 to 17f5df52a7d9ed6bb12d3b1768460def84

### PR DESCRIPTION
**Pull request by goroi**
Add 5.4.95-42.163.amzn2.x86_64 to 17f5df52a7d9ed6bb12d3b1768460def84
Signed-off-by:  goroi <georgi.ivanov77@gmail.com>

### CODE REVIEW

**Comment by jonahjon** [comment]
Hey @goroi  If you change the 
`kernelrelease: amazonlinux2_5.4.95-42.163.amzn2.x86_64` -> `kernelrelease: 5.4.95-42.163.amzn2.x86_64`  I think this will work.

**Comment by goroi** [comment]
@jonahjon sorry for the previous PR , it had a typo in kernelrelease

**Comment by goroi** [comment]
> Hey @goroi If you change the
> `kernelrelease: amazonlinux2_5.4.95-42.163.amzn2.x86_64` -> `kernelrelease: 5.4.95-42.163.amzn2.x86_64` I think this will work.

Typo fixed.

**Comment by goroi** [comment]
Hi @jonahjon , thanks,  I pushed a new PR with the fix.

> Hey @goroi If you change the
> `kernelrelease: amazonlinux2_5.4.95-42.163.amzn2.x86_64` -> `kernelrelease: 5.4.95-42.163.amzn2.x86_64` I think this will work.

**Comment by jonahjon** [comment]
> Hi @jonahjon , thanks, I pushed a new PR with the fix.
> 
> > Hey @goroi If you change the
> > `kernelrelease: amazonlinux2_5.4.95-42.163.amzn2.x86_64` -> `kernelrelease: 5.4.95-42.163.amzn2.x86_64` I think this will work.

Awesome, looks good

**Comment by jonahjon** [comment]
Awesome, looks good although you will might need to do an interactive, and sign that last commit for the bot.

**Review by jonahjon — APPROVED** [review]

**Pull request merged**
