### PR TITLE
Add job to generate configs from crawled kernels

### PR DESCRIPTION
**Pull request by maxgio92**
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>

/cc @FedeDP

### CODE REVIEW

**Comment by maxgio92** [comment]
As an example, see #685

**Comment by FedeDP** [comment]
I think this *should* be safe to merge, given that old configs are untouched, only new ones are pushed, right?
Basically, only side effect could be that newly added configs are all broken (ie: driverkit is not able to build them).

I see that #685 had some lines removed though: `+106,689 −4 `; i am not able to understand where they were removed though, github is failing bad with so many touched files :)

**Comment by maxgio92** [comment]
Please consider @FedeDP that the PR #685 goal was to test the PR opening feature, from the related test branch with results already in place.

Anyway, this PR would be append-only on distribution (published pre-built drivers). Instead, some configuration could be changed. The latter can't be assumed to be false (e.g. consider a wrong-written configuration that now will be generated).

**Comment by FedeDP** [comment]
Once this is in, i will create a wip PR on top of this to support arm64 drivers build; it should be fairly simple to achieve.

**Comment by maxgio92** [comment]
Do we want @FedeDP to replace `ubuntu-gke` to be treated by Driverkit as a `ubuntu-generic` Ubuntu flavour?
I think we can start simple and then optimize to increase coverage, but I don't have strong opinions on that.

**Comment by FedeDP** [comment]
I think it would be better to fix it now, as it is needed to correctly build that Ubuntu flavour!

**Comment by maxgio92** [comment]
As a side note: I added a `validate` Make target in the DBG, so that we separately validate configurations. In turn the build targets call it.

**Comment by maxgio92** [comment]
@FedeDP @zuc #695 if approved, should be merged before to fix the CI that now is not working

**Comment by maxgio92** [comment]
I agree @FedeDP 

/hold

**Review by zuc — APPROVED** [review]

**Pull request merged**
