### PR TITLE
prow for cloudnativesecurityhub* repos

### LINKED ISSUE #68: Add poiana to cloud native security hub repos
We need to setup Prow workflow for these repositories:

- https://github.com/falcosecurity/cloud-native-security-hub
- https://github.com/falcosecurity/cloud-native-security-hub-frontend
- https://github.com/falcosecurity/cloud-native-security-hub-backend

## Subtasks

- [x] OWNERS (approvals, and reviewers)
- [x] kind labels
- [ ] protect master branches
- [ ] enforce rebase merging strategy
- [ ] release notes (changelog) mechanism from PRs
- [ ] do not merge strategies (WIP, needs rebase, missing release notes, invalid owners)
- [ ] detect missing kind/* labels (issues, PR)
- [ ] plugins

cc @nestorsalceda @bencer

### PR DESCRIPTION
**Pull request by leodido**
See issue #68 for more details about the configs and plugins this PR puts in place for the cloud-native-security-hub* repositories.

I need @bencer and @nestorsalceda at least to take a look at this before merging.

Fixes #68.

### CODE REVIEW

**Comment by nestorsalceda** [comment]
Looks good to me @leodido 

Thank you very much for helping with this, my friend :)

**Comment by leodido** [comment]
Thanks to you for your amazing work on Cloud Native Security Hub (and not only there!) @nestorsalceda 🤗 

A question: all the three projects will have separate changelogs?
Or do you plan to have only on changelog for the whole thing (if yes, in which repo of the 3) ?

**Comment by bencer** [comment]
looks good to me @leodido !

**Comment by fntlnz** [comment]
Approwed

**Pull request merged**
