### PR TITLE
update(persons): add fededp

### PR DESCRIPTION
**Pull request by FedeDP**
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

### CODE REVIEW

**Comment by Issif** [comment]
Can you sign-off the commit too, please.

**Comment by FedeDP** [comment]
It is... am i missing something?

**Comment by FedeDP** [comment]
Uh didn't notice. Perhaps prow was slowly dying when i pushed, and it lost the webhook; it happens sometimes.

**Comment by Issif** [comment]
I see same behavior in other PR, even older.

**Review by zuc — APPROVED** [review]
/approve

**Pull request merged**
