### PR TITLE
Backfill all missing AmazonLinux2 kernel versions for kmod and ebpf probe building

### PR DESCRIPTION
**Pull request by abroglesc**
This PR attempts to ensure we are building the probe/kmod for all AmazonLinux2 kernels that exist today.

To accomplish this, I wrote a script to attempt to pull all kernels versions from the yum repos that exist on AmazonLinux2 and get all of these pre-built for existing kernels.

The can be ran from an AL2 x86_64 ec2 instance instance and is as follows:
```python
import yum
​
​
def main():
    yb = yum.YumBase()
    yb.preconf.debuglevel = 0
    yb.preconf.errorlevel = 0
    yb.update()
    available_kernels = yb.searchPackages(['name'], ['kernel-headers'])
    list_of_versions = []
    for pkg in available_kernels.keys():
        list_of_versions.append("{}-{}.{}".format(pkg.version, pkg.release, pkg.arch))
​
    for version in sorted(list_of_versions):
        print(version)
​
if __name__ == "__main__":
    main()
```

For this, I used an ec2 instance with a 5.10 kernel and that had default yum repos which contained headers for 5.10 and 4.x kernels but for the 5.4.* kernels I needed to add an extra repo to my yum repos which is:
```
[amzn2extra-kernel-5.4]
enabled = 1
name = Amazon Extras repo for kernel-5.4
mirrorlist = $awsproto://$amazonlinux.$awsregion.$awsdomain/$releasever/extras/kernel-5.4/latest/$basearch/mirror.list
gpgcheck = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-2
priority = 10
skip_if_unavailable = 1
report_instanceid = yes
```

After doing the above I was able to populate what I believe to be the list of all AL2 kernel versions available today which is:
```
4.14.101-91.76.amzn2.x86_64
4.14.104-95.84.amzn2.x86_64
4.14.106-97.85.amzn2.x86_64
4.14.109-99.92.amzn2.x86_64
4.14.114-103.97.amzn2.x86_64
4.14.114-105.126.amzn2.x86_64
4.14.121-109.96.amzn2.x86_64
4.14.123-111.109.amzn2.x86_64
4.14.128-112.105.amzn2.x86_64
4.14.133-113.105.amzn2.x86_64
4.14.133-113.112.amzn2.x86_64
4.14.138-114.102.amzn2.x86_64
4.14.143-118.123.amzn2.x86_64
4.14.146-119.123.amzn2.x86_64
4.14.146-120.181.amzn2.x86_64
4.14.152-124.171.amzn2.x86_64
4.14.152-127.182.amzn2.x86_64
4.14.154-128.181.amzn2.x86_64
4.14.158-129.185.amzn2.x86_64
4.14.165-131.185.amzn2.x86_64
4.14.165-133.209.amzn2.x86_64
4.14.171-136.231.amzn2.x86_64
4.14.173-137.228.amzn2.x86_64
4.14.173-137.229.amzn2.x86_64
4.14.177-139.253.amzn2.x86_64
4.14.177-139.254.amzn2.x86_64
4.14.181-140.257.amzn2.x86_64
4.14.181-142.260.amzn2.x86_64
4.14.186-146.268.amzn2.x86_64
4.14.192-147.314.amzn2.x86_64
4.14.193-149.317.amzn2.x86_64
4.14.198-152.320.amzn2.x86_64
4.14.200-155.322.amzn2.x86_64
4.14.203-156.332.amzn2.x86_64
4.14.209-160.335.amzn2.x86_64
4.14.209-160.339.amzn2.x86_64
4.14.214-160.339.amzn2.x86_64
4.14.219-161.340.amzn2.x86_64
4.14.219-164.354.amzn2.x86_64
4.14.225-168.357.amzn2.x86_64
4.14.225-169.362.amzn2.x86_64
4.14.231-173.360.amzn2.x86_64
4.14.231-173.361.amzn2.x86_64
4.14.232-176.381.amzn2.x86_64
4.14.232-177.418.amzn2.x86_64
4.14.238-182.421.amzn2.x86_64
4.14.238-182.422.amzn2.x86_64
4.14.241-184.433.amzn2.x86_64
4.14.243-185.433.amzn2.x86_64
4.14.246-187.474.amzn2.x86_64
4.14.248-189.473.amzn2.x86_64
4.14.252-195.481.amzn2.x86_64
4.14.252-195.483.amzn2.x86_64
4.14.256-197.484.amzn2.x86_64
4.14.26-54.32.amzn2.x86_64
4.14.262-200.489.amzn2.x86_64
4.14.268-205.500.amzn2.x86_64
4.14.273-207.502.amzn2.x86_64
4.14.33-59.34.amzn2.x86_64
4.14.33-59.37.amzn2.x86_64
4.14.42-61.37.amzn2.x86_64
4.14.47-63.37.amzn2.x86_64
4.14.47-64.38.amzn2.x86_64
4.14.51-66.38.amzn2.x86_64
4.14.55-68.37.amzn2.x86_64
4.14.59-68.43.amzn2.x86_64
4.14.62-70.117.amzn2.x86_64
4.14.67-71.56.amzn2.x86_64
4.14.70-72.55.amzn2.x86_64
4.14.72-73.55.amzn2.x86_64
4.14.77-80.57.amzn2.x86_64
4.14.77-81.59.amzn2.x86_64
4.14.77-86.82.amzn2.x86_64
4.14.88-88.73.amzn2.x86_64
4.14.88-88.76.amzn2.x86_64
4.14.94-89.73.amzn2.x86_64
4.14.97-90.72.amzn2.x86_64
4.9.62-10.57.amzn2.x86_64
4.9.70-2.243.amzn2.x86_64
4.9.75-1.56.amzn2.x86_64
4.9.76-38.79.amzn2.x86_64
4.9.77-41.59.amzn2.x86_64
4.9.81-44.57.amzn2.x86_64
4.9.85-46.56.amzn2.x86_64
4.9.85-47.59.amzn2.x86_64
5.10.102-99.473.amzn2.x86_64
5.10.106-102.504.amzn2.x86_64
5.10.29-27.126.amzn2.x86_64
5.10.29-27.128.amzn2.x86_64
5.10.35-31.135.amzn2.x86_64
5.10.47-39.130.amzn2.x86_64
5.10.50-44.131.amzn2.x86_64
5.10.50-44.132.amzn2.x86_64
5.10.59-52.142.amzn2.x86_64
5.10.62-55.141.amzn2.x86_64
5.10.68-62.173.amzn2.x86_64
5.10.75-79.358.amzn2.x86_64
5.10.82-83.359.amzn2.x86_64
5.10.93-87.444.amzn2.x86_64
5.10.96-90.460.amzn2.x86_64
5.4.105-48.177.amzn2.x86_64
5.4.110-54.182.amzn2.x86_64
5.4.110-54.189.amzn2.x86_64
5.4.117-58.216.amzn2.x86_64
5.4.129-62.227.amzn2.x86_64
5.4.129-63.229.amzn2.x86_64
5.4.141-67.229.amzn2.x86_64
5.4.144-69.257.amzn2.x86_64
5.4.149-73.259.amzn2.x86_64
5.4.156-83.273.amzn2.x86_64
5.4.162-86.275.amzn2.x86_64
5.4.172-90.336.amzn2.x86_64
5.4.176-91.338.amzn2.x86_64
5.4.181-99.354.amzn2.x86_64
5.4.186-102.354.amzn2.x86_64
5.4.20-12.75.amzn2.x86_64
5.4.38-17.76.amzn2.x86_64
5.4.46-19.75.amzn2.x86_64
5.4.46-23.77.amzn2.x86_64
5.4.50-25.83.amzn2.x86_64
5.4.58-27.104.amzn2.x86_64
5.4.58-32.125.amzn2.x86_64
5.4.68-34.125.amzn2.x86_64
5.4.74-36.135.amzn2.x86_64
5.4.80-40.140.amzn2.x86_64
5.4.91-41.139.amzn2.x86_64
5.4.95-42.163.amzn2.x86_64
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Hi @abroglesc ! 
Thanks for this, it's great!
Note, moreover, that me and @maxgio92 are working together towards a solution similar to this: https://github.com/FedeDP/kernel-crawler and https://github.com/maxgio92/krawler.
Basically, the idea is to crawl all available kernels from various distro and push a "registry" (ie: a json list) in a repo; the registry will be then consumed by a cron job on test-infra (monthly?) to automatically add any new config for new kernels.

I am currently fixing https://github.com/FedeDP/kernel-crawler registry output to better match DriverKit config files; i have an open PR to donate it to falcosecurity too!
Then, i'll surely open a PR on test-infra to add the cron job :)

Max is instead working on his own krawler that will hopefully someday replace the kernel-crawler to better suit DriverKit use case from ground up (and moreover it is also written in golang vs python).

Note that my kernel-crawler is a fork of https://github.com/draios/probe-builder/tree/dev/probe_builder/kernel_crawler, on top of that i just added support for arm64 and json output (+ driverkit-like output).

Btw this looks really neat, i can't approve but of course :+1:  from me!

**Comment by abroglesc** [comment]
Tests all passed @zuc 🎉 please let me know if this is good to merge

**Review by zuc — APPROVED** [review]

**Comment by zuc** [comment]
@abroglesc thanks for your contribution!

**Comment by maxgio92** [comment]
Thank you @abroglesc, you totally hit the nail on the head!
I confirm what @FedeDP said. Personally, I started working on my crawler for this exact reason. The crawler @FedeDP is working on is almost completed and I'd like to integrate it with the pipeline, as it already support a lot of distros.
What is missing is only a connector to match the data model in output and the one that [Driverkit](https://github.com/falcosecurity/driverkit) will consume.

**Pull request merged**
