### PR TITLE
update(dbg): added new 3.0.1+driver configs.

### PR DESCRIPTION
**Pull request by FedeDP**
Moreover, removed old, non-released, 3.0.0+driver configs.

Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

### CODE REVIEW

**Review by zuc — APPROVED** [review]

**Comment by FedeDP** [comment]
It will work if we try hard enough :joy:

**Comment by Andreagit97** [comment]
A retest a day keeps poiana away

**Comment by FedeDP** [comment]
/retest

This time it should finally work considering that we manually built and published drivers on download.falco.org.

**Comment by leogr** [comment]
> /retest
> 
> This time it should finally work considering that we manually built and published drivers on download.falco.org.

Uploading still in progress

**Pull request merged**
