### PR TITLE
update(images): bumped build-drivers driverkit to 0.10.2

### PR DESCRIPTION
**Pull request by FedeDP**
Moreover, dropped some useless checks for output-module and output probe in `generate` script: now driverkit(since 0.10.2) is smart enough to disable (with a warning) unsupported outputs.

### CODE REVIEW

**Comment by FedeDP** [comment]
Me and @alacuku  spotted a small regression for minikube in driverkit 0.10.1; we will fix it asap and bump this PR to 0.10.2 once it gets released.

**Comment by alacuku** [comment]
falcosecurity/driverkit#225

**Comment by FedeDP** [comment]
Bumped to 0.10.2 +
> Moreover, dropped some useless checks for output-module and output probe in generate script: now driverkit(since 0.10.2) is smart enough to disable (with a warning) unsupported outputs.

**Review by zuc — APPROVED** [review]

**Pull request merged**
