### PR TITLE
cleanup(config/clusters/ecr.tf): autobump ecr force delete.

### PR DESCRIPTION
**Pull request by cappellinsamuele**
This PR forces delete `autobump` ecr resource.

### CODE REVIEW

**Comment by maxgio92** [comment]
Are we sure we want to prune the repository @cappellinsamuele?

**Comment by cappellinsamuele** [comment]
> Are we sure we want to prune the repository @cappellinsamuele?

Maybe it is better to wait until we are sure everything is ok

**Comment by maxgio92** [comment]
Let's put this on hold :)

/hold

**Comment by maxgio92** [comment]
Let's wait for #1132

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
#1132 was merged!

**Pull request merged**
