### PR TITLE
Add configs for amazonlinux2_5.4.196-108.356.amzn2.x86_64_1

### PR DESCRIPTION
**Pull request by 0xIAN**

### CODE REVIEW

**Comment by maxgio92** [comment]
Hey @darknesssheep we were waiting for test jobs on driver building to complete. They are now, so we can now go on :-)

**Review by maxgio92 — APPROVED** [review]
/approve

**Comment by maxgio92** [comment]
Publishing job are now working [here](https://prow.falco.org/view/s3/falco-prow-logs/logs/build-new-drivers-amazonlinux2-postsubmit/1539878737632301056) @darknesssheep, you can give it a check

**Comment by darknesssheep** [comment]
thx I'll @maxgio92 :)

**Pull request merged**
