### PR TITLE
Add new kernel add_5.4.209-116.363.amzn2.x86_64

### PR DESCRIPTION
**Pull request by berkil**
Signed-off-by: Boris Bakshiyev <boris.bakshiyev@payu.com>

### CODE REVIEW

**Comment by berkil** [comment]
Should I add anything to make the test pass?

**Comment by leogr** [comment]
> @berkil: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> build-new-drivers-amazonlinux2-presubmit	[0ad4a62](https://github.com/falcosecurity/test-infra/commit/0ad4a625670a180cce3cd2a23bf11b718d94d35e)	[link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_test-infra/814/build-new-drivers-amazonlinux2-presubmit/1565272855447343104)	true	`/test build-new-drivers-amazonlinux2-presubmit`
> [Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=test-infra&pr=814). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/test-infra/issues?q=is:issue+is:open) when you hit one in your PR.

cc @FedeDP 

```
make: *** No rule to make target '39ae7d40496793cf3d3e7890c9bbdc202263836b_amazonlinux2_5.4.209-116.363.amzn2.x86_64_1', needed by 'specific_target_old'.  Stop.
```

:thinking:

**Comment by FedeDP** [comment]
I am not sure, but this kernel will be uploaded as part of the kernel-crawler automation: https://github.com/falcosecurity/test-infra/pull/824/files#diff-af1b8ca64e82bdb34fefd6cf556d33328e0d4c347a2690e5ab3e60684e5652bf.


The driver itself was correctly built on that PR:
```
 utils/checkfiles config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_5.4.209-116.363.amzn2.x86_64_1.yaml
DRIVERKIT=/bin/driverkit S3_DRIVERS_BUCKET="falco-distribution" S3_DRIVERS_KEY_PREFIX="driver" SKIP_EXISTING=true DRIVERKIT_BACKEND=docker DRIVERKIT_EXTRA_ARGS="" utils/build config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_5.4.209-116.363.amzn2.x86_64_1.yaml
INFO using config file                             file=config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_5.4.209-116.363.amzn2.x86_64_1.yaml
INFO driver building, it will take a few seconds   processor=docker
INFO kernel module available                       path=output/39ae7d40496793cf3d3e7890c9bbdc202263836b/falco_amazonlinux2_5.4.209-116.363.amzn2.x86_64_1.ko
INFO eBPF probe available                          path=output/39ae7d40496793cf3d3e7890c9bbdc202263836b/falco_amazonlinux2_5.4.209-116.363.amzn2.x86_64_1.o 
```
So, as soon as the PR is merged, and the `postsubmit` jobs do their jobs, the kernel will be available on download.falco.org.

**Comment by berkil** [comment]
So I should close the PR in favor of https://github.com/falcosecurity/test-infra/pull/824 ?

**Comment by leogr** [comment]
> So I should close the PR in favor of #824 ?

Before deciding, let's see if #824's building process completes and gets merged.

**Comment by berkil** [comment]
> > So I should close the PR in favor of #824 ?
> 
> Before deciding, let's see if #824's building process completes and gets merged.

#824 is merged

**Comment by FedeDP** [comment]
Hi! The new kernel should be now ready in download.falco.org.
Care to try?

**Comment by FedeDP** [comment]
Yay! You can close this one then :)

**Pull request closed without merging**
