### PR TITLE
add ubuntu-aws_5.3.0-1035-aws_37

### PR DESCRIPTION
**Pull request by wahern-splunk**

### CODE REVIEW

**Comment by evanmcclure** [comment]
+1

**Review by leodido — CHANGES_REQUESTED** [review]
Thanks for sending this! :)

Anyways, two considerations:
- would you please sign-off your commit?
- also, by looking at the build system I noticed both the configs are not building (error:`FATA exiting                                       error="specific kernel headers not found"`): have you tried building them locally by using https://github.com/falcosecurity/driverkit and the same config files?

**Comment by wahern-splunk** [comment]
> (error:FATA exiting error="specific kernel headers not found"): have you tried building them locally by using https://github.com/falcosecurity/driverkit and the same config files?

Ok, just did and it looks like everything beyond aws_34 is failing: ubuntu-aws_5.3.0-1033-aws_35.yaml, ubuntu-aws_5.3.0-1034-aws_36.yaml, and ubuntu-aws_5.3.0-1035-aws_37.yaml.

**Comment by wahern-splunk** [comment]
So it seems that the URLs embedded in driverkit:pkg/driverbuilder/builder/ubuntu.go are insufficient. The binary package for versions above aws_34 can be found at https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-aws-5.3/.

I don't know anything about their naming scheme and why this might be.

**Comment by wahern-splunk** [comment]
Below is a patch to the driverkit source code that fixes the issue (NB: only tested with ubuntu-aws-5.3.0-103* builds to save time.) But it's clear the source code is making many assumptions regarding Ubuntu repository and package naming schemes the reasons for which I'm ignorant, so I doubt you'd want to apply the patch.

```
diff --git a/pkg/driverbuilder/builder/ubuntu.go b/pkg/driverbuilder/builder/ubuntu.go
index c3e5b6d..30bb006 100644
--- a/pkg/driverbuilder/builder/ubuntu.go
+++ b/pkg/driverbuilder/builder/ubuntu.go
@@ -76,7 +76,7 @@ func (v ubuntuAWS) Script(c Config) (string, error) {
 	kr := kernelrelease.FromString(c.Build.KernelRelease)
 
 	urls, err := ubuntuAWSHeadersURLFromRelease(kr, c.Build.KernelVersion)
-	if len(urls) != 2 {
+	if len(urls) == 0 {
 		return "", fmt.Errorf("specific kernel headers not found")
 	}
 
@@ -103,6 +103,8 @@ func ubuntuAWSHeadersURLFromRelease(kr kernelrelease.KernelRelease, kv uint16) (
 	baseURL := []string{
 		"https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-aws",
 		"http://security.ubuntu.com/ubuntu/pool/main/l/linux-aws",
+		"https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-aws-5.3",
+		"https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-aws-5.4",
 	}
 
 	for _, u := range baseURL {
@@ -173,6 +175,15 @@ func fetchUbuntuGenericKernelURL(baseURL string, kr kernelrelease.KernelRelease,
 func fetchUbuntuAWSKernelURLS(baseURL string, kr kernelrelease.KernelRelease, kernelVersion uint16) []string {
 	firstExtra := extractExtraNumber(kr.Extraversion)
 	return []string{
+		fmt.Sprintf(
+			"%s/linux-aws-5.3-headers-%s-%s_%s-%s.%d_all.deb",
+			baseURL,
+			kr.Fullversion,
+			firstExtra,
+			kr.Fullversion,
+			firstExtra,
+			kernelVersion,
+		),
 		fmt.Sprintf(
 			"%s/linux-aws-headers-%s-%s_%s-%s.%d_all.deb",
 			baseURL,
```

**Comment by leodido** [comment]
@wahern-splunk thanks for your investigation!

I've continued it and I found the real issue: it was in the way we parse the `ubuntu-aws-*.*` (eg. [this one](https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-aws-5.3/)) pages to look for kernel headers.

As soon https://github.com/falcosecurity/driverkit is released your config files will build.

**Comment by wahern-splunk** [comment]
I tested the latest driverkit master against this branch and all appears to compile cleanly, now.

**Comment by leodido** [comment]
Perfect!

Soon to be merged in!

**Review by leodido — APPROVED** [review]
🥳

**Pull request merged**
