### PR TITLE
new(config): added amazonlinux2023 build-drivers jobs.

### PR DESCRIPTION
**Pull request by FedeDP**
/hold 
until:
- [x] https://github.com/falcosecurity/kernel-crawler/pull/118
- [x] https://github.com/falcosecurity/driverkit/pull/268
- [x] https://github.com/falcosecurity/falco/pull/2494

### CODE REVIEW

**Comment by FedeDP** [comment]
We also need a new driverkit tag and bumping it here!

**Comment by FedeDP** [comment]
Rebased on top of master!

**Comment by FedeDP** [comment]
The PR to bump driverkit is opened: #1160 
/unhold

**Review by maxgio92 — APPROVED** [review]
/approve

Awesome!

**Pull request merged**
