### PR TITLE
chore: config for amazonlinux2_5.4.201-111.359

### PR DESCRIPTION
**Pull request by saahn**

### CODE REVIEW

**Comment by leogr** [comment]
Hey @saahn 

Could you [sign off](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) your commits, please?

Otherwise, we can't merge this PR. Thank you :pray:

**Comment by saahn** [comment]
@leogr Thank you for the response. I recently learned that my company requires a LICENSE file to be present in the repository before I can submit a PR to it. I opened an issue for it here: https://github.com/falcosecurity/test-infra/issues/780 
I will unfortunately have to wait until that is in place before I can sign off on the PR.

**Comment by leogr** [comment]
Oh you are totally right. We missed it. I'll try to fix it soon. Thank you

**Comment by leogr** [comment]
Hey @saahn 

The license file has been added by #781 . Thank you for having reported that issue :pray: 

Your PR SGMT, but could you [sign off](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) your commits pls? Otherwise, we can't merge the PR.

Thank you, again.

**Comment by saahn** [comment]
HI @leogr , thanks for getting the LICENSE file added. I've signed-off on the commit. 
Thank you so much for your help!

**Comment by saahn** [comment]
Hi @leogr , it looks like the PR needs to be officially approved by you or one of the other OWNERs with a `/lgtm` comment.  Can you please approve when you get a chance? Thank you again!

**Comment by maxgio92** [comment]
Hey @saahn thank you. I just triggered jobs to test your PR :-)

**Review by maxgio92 — APPROVED** [review]
/approve

Thank you @saahn

**Pull request merged**
