### PR TITLE
Add latest Amazon Linux 2 kernel version

### PR DESCRIPTION
**Pull request by marizmendi**

### CODE REVIEW

**Review by leodido — COMMENTED** [review]
Thanks @marizmendi, would you please add the same config for the other Falco driver versions? :)

**Review by leodido — APPROVED** [review]

**Review by jonahjon — APPROVED** [review]

**Comment by jonahjon** [comment]
@leodido It looks like these all passed, should we remove hold?

**Comment by leodido** [comment]
Superseded by https://github.com/falcosecurity/test-infra/pull/339 and https://github.com/falcosecurity/driverkit/pull/92

Thanks @marizmendi for your contribution anyway!

/close

**Pull request closed without merging**
