### PR TITLE
Fix images approval: publish after PR approval

### LINKED ISSUE #421: Images are built and published before PRs are merged
**Describe the bug**

Images are built and published before PRs are merged. I think this is an issue.

**How to reproduce it**

As in this case (#419), the drivers have been built using a `build-drivers` version that has been published before the related PR (#410) has been merged.

**Expected behaviour**

No new version should be released and published before the PR being merged.

**Additional context**

We're currently building and publishing CI base container images before the approval with [presubmit jobs](https://github.com/falcosecurity/test-infra/blob/master/config/jobs/build-prow-images/build-images.yaml).
Obviously this comes with security and applications lifecycle concerns.

### PR DESCRIPTION
**Pull request by maxgio92**
This PR should prevent from publishing CI base images before approving the related PRs.

Fixes #421.

### CODE REVIEW

**Review by leogr — APPROVED** [review]

**Comment by jonahjon** [comment]
Love the idea, slightly confused though about how you would even test the built image before you merge the PR on this though. 

Are you just testing the image builds in this case without error.

**Pull request merged**
