### PR TITLE
add kernel module for amazonlinux2_5.4.235-144.344.amzn2.x86_64

### PR DESCRIPTION
**Pull request by Kaizhe**

### CODE REVIEW

**Comment by FedeDP** [comment]
Hi! thanks for this PR!
Why did you remove the kernelurls? They are really helpful to be able to build the driver! :)

**Comment by Kaizhe** [comment]
> Hi! thanks for this PR! Why did you remove the kernelurls? They are really helpful to be able to build the driver! :)

Looks like the ko is there already.  Not sure why I can't download it:

```
* Looking for a falco module locally (kernel 5.4.235-144.344.amzn2.x86_64)
30
* Trying to download a prebuilt falco module from https://download.falco.org/driver/39ae7d40496793cf3d3e7890c9bbdc202263836b/falco_amazonlinux2_5.4.235-144.344.amzn2.x86_64_1.ko
29
curl: (22) The requested URL returned error: 404
28
Unable to find a prebuilt falco module
27
* Trying to dkms install falco module with GCC /usr/bin/gcc
26
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
25
24
Creating symlink /var/lib/dkms/falco/39ae7d40496793cf3d3e7890c9bbdc202263836b/source ->
23
                 /usr/src/falco-39ae7d40496793cf3d3e7890c9bbdc202263836b
22
21
DKMS: add completed.
20
* Running dkms build failed, couldn't find /var/lib/dkms/falco/39ae7d40496793cf3d3e7890c9bbdc202263836b/build/make.log (with GCC /usr/bin/gcc)
19
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
18
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
17
* Running dkms build failed, couldn't find /var/lib/dkms/falco/39ae7d40496793cf3d3e7890c9bbdc202263836b/build/make.log (with GCC /usr/bin/gcc-8)
16
* Trying to dkms install falco module with GCC /usr/bin/gcc-6
15
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
14
* Running dkms build failed, couldn't find /var/lib/dkms/falco/39ae7d40496793cf3d3e7890c9bbdc202263836b/build/make.log (with GCC /usr/bin/gcc-6)
13
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
12
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
11
* Running dkms build failed, couldn't find /var/lib/dkms/falco/39ae7d40496793cf3d3e7890c9bbdc202263836b/build/make.log (with GCC /usr/bin/gcc-5)
10
* Trying to load a system falco module, if present
9
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
8
Fri Apr 14 19:26:37 2023: Falco version 0.32.0 (driver version 39ae7d40496793cf3d3e7890c9bbdc202263836b)
7
Fri Apr 14 19:26:37 2023: Falco initialized with configuration file /etc/falco/falco.yaml
6
Fri Apr 14 19:26:37 2023: Loading rules from file /etc/falco/falco_rules.yaml:
5
Fri Apr 14 19:26:38 2023: Loading rules from file /etc/falco/falco_rules.local.yaml:
4
Fri Apr 14 19:26:38 2023: Loading rules from file /etc/falco/rules.d/falco_rules.aurora.yaml:
3
Fri Apr 14 19:26:38 2023: Starting internal webserver, listening on port 8765
2
Fri Apr 14 19:26:38 2023: Unable to load the driver.
1
Fri Apr 14 19:26:38 2023: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.
```

**Comment by FedeDP** [comment]
Oh right. The driver is already built but you are running an outdated Falco version whose driver version is not supported anymore.
We only support latest 3 driver versions!:grinning:

**Comment by Kaizhe** [comment]
> Oh right. The driver is already built but you are running an outdated Falco version whose driver version is not supported anymore. We only support prebuilt drivers for latest 3 driver versions!😀

hey @FedeDP can you do me a favor to build the ko for me. This is production.

**Comment by FedeDP** [comment]
I can do much better than that :) i can share the super simple command to build it yourself! :)
```
docker run -v /var/run/docker.sock:/var/run/docker.sock -ti --rm falcosecurity/driverkit:latest driverkit docker --kernelrelease 5.4.235-144.344.amzn2.x86_64 --target amazonlinux2 --output-module /tmp/al2.ko --kernelurls "http://amazonlinux.us-east-1.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/437c15a145ce03d3a48b7fd7559df3851f3b58fd9d7a78960f44d029f145bd61/../../../../../../blobstore/8cb33943794efdff1178a8c611a779714e1d13297e82d7d49317bc2c59ad67cb/kernel-devel-5.4.235-144.344.amzn2.x86_64.rpm" --driverversion 39ae7d40496793cf3d3e7890c9bbdc202263836b
```

You'll find the ko under `/tmp/al2.ko` :)

**Comment by Kaizhe** [comment]
> I can do much better than that :) i can share the super simple command to build it yourself!
> 
> ```
> docker run -v /var/run/docker.sock:/var/run/docker.sock -ti --rm falcosecurity/driverkit:latest driverkit docker --kernelrelease 5.4.235-144.344.amzn2.x86_64 --target amazonlinux2 --output-module /tmp/al2.ko --kernelurls "http://amazonlinux.us-east-1.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/437c15a145ce03d3a48b7fd7559df3851f3b58fd9d7a78960f44d029f145bd61/../../../../../../blobstore/8cb33943794efdff1178a8c611a779714e1d13297e82d7d49317bc2c59ad67cb/kernel-devel-5.4.235-144.344.amzn2.x86_64.rpm" --driverversion 39ae7d40496793cf3d3e7890c9bbdc202263836b
> ```
> 
> You'll find the ko under `/tmp/al2.ko` 😄

We have about 20 EKS clusters total with multiple thousand nodes, I couldn't image how to distribute the ko.  Can you just make the download link available ?

**Comment by FedeDP** [comment]
Uh that's a bit harder then; i don't have write access to the s3 bucket :/ I think you are out of luck (ie: you must find a different way to distribute the artifact yourself) since we are not supporting prebuilt for that driver version anymore!

**Comment by roee-landesman** [comment]
I'm in the same situation (with EKS). Is the advisable course of action to downgrade our Falco version via helm?

**Comment by Kaizhe** [comment]
Keeping latest 3 versions is not enough, enterprise may have a much slower patching cycle.

**Comment by FedeDP** [comment]
It's not like we only keep latest 3, we actively provide updates to prebuilt drivers for latest 3.
S3 space and computation time has a cost too unfortunately...
Btw it can be discussed with the broader community.
/hold

**Comment by FedeDP** [comment]
@leogr @zuc @maxgio92

**Comment by leogr** [comment]
> > I can do much better than that :) i can share the super simple command to build it yourself!
> > 
> > ```
> > docker run -v /var/run/docker.sock:/var/run/docker.sock -ti --rm falcosecurity/driverkit:latest driverkit docker --kernelrelease 5.4.235-144.344.amzn2.x86_64 --target amazonlinux2 --output-module /tmp/al2.ko --kernelurls "http://amazonlinux.us-east-1.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/437c15a145ce03d3a48b7fd7559df3851f3b58fd9d7a78960f44d029f145bd61/../../../../../../blobstore/8cb33943794efdff1178a8c611a779714e1d13297e82d7d49317bc2c59ad67cb/kernel-devel-5.4.235-144.344.amzn2.x86_64.rpm" --driverversion 39ae7d40496793cf3d3e7890c9bbdc202263836b
> > ```
> > 
> > You'll find the ko under `/tmp/al2.ko` 😄
> 
> We have about 20 EKS clusters total with multiple thousand nodes, I couldn't image how to distribute the ko.  Can you just make the download link available ? 

Hey @Kaizhe 

Distributing your own ko is easy:

> You can use the env variable DRIVERS_REPO to override the default repository URL for prebuilt drivers. The URL must not have the trailing slash, i.e. https://myhost.mydomain.com or if the server has a subdirectories structure https://myhost.mydomain.com/drivers

See https://falco.org/docs/getting-started/installation/

On the other hand, I'm not totally convinced we can manage too many old versions on Falcosecurity (the computational cost may be huge, also the maintenance).

Anyway, I'm totally open to any solution that can help our adopters.

**Comment by FedeDP** [comment]
I was thinking about starting to deliver "LTS" releases. Like, releases that should be focused on bug fixing and have 2yrs of support (for drivers and eventual patch releases). But this has a larger scope and should be discussed as a proposal.
I think it would be a great sign of maturity for the project though.

**Comment by maxgio92** [comment]
Unfortunately as @leogr and @FedeDP said, maintaining support of prebuilt drivers for one Falco release means building tens of thousands of kernel release targets to build against.

We could think about increasing the number but at the end of the day I'm not sure would solve the issue of this scenario.

I like the idea of @FedeDP about LTS as it would be the exact match for the use case. What do you think about that @Kaizhe?

**Comment by leogr** [comment]
PS

I'm not against LTS if we reach consensus. However, I guess we need help for that, since available cycles of current maintainers are not enough, IMO

**Comment by FedeDP** [comment]
@leogr Agree, of course.

**Comment by Kaizhe** [comment]
> DRIVERS_REPO

@leogr it works for me (though I started the upgrade), as I put myself on other Falco users' shoes, this is sort of forcing people to upgrade from time to time.  Do you have any insight of the different distro where ko got built and downloaded? In my case, amazon linux 2 is a the main one, can we keep older version for the top 5 distros?

**Comment by maxgio92** [comment]
@Kaizhe which retention count would be a minimal one in the scenarios you're used to?

**Pull request closed without merging**
